name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  prettier-format-check:
    name: Check
    uses: bymbly/gha-workflows/.github/workflows/prettier-format-check.yaml@main

  eslint-lint-check:
    name: Check
    uses: bymbly/gha-workflows/.github/workflows/eslint-lint-check.yaml@main

  markdown-lint-check:
    name: Check
    uses: bymbly/gha-workflows/.github/workflows/markdown-lint-check.yaml@main

  stylelint-lint-check:
    name: Check / Stylelint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: bymbly/gha-workflows/.github/actions/setup-node@main
        with:
          cache: "npm"
      - run: npm ci
      - run: npx stylelint "**/*.css"

  astro-check:
    name: Check / Astro Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: bymbly/gha-workflows/.github/actions/setup-node@main
        with:
          cache: "npm"
      - run: npm ci
      - run: npx astro check

  deploy:
    name: Deploy
    needs:
      [
        prettier-format-check,
        eslint-lint-check,
        markdown-lint-check,
        stylelint-lint-check,
        astro-check,
      ]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: bymbly/gha-workflows/.github/actions/setup-node@main
        with:
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
